services:
  web:
    build: .
    command:
      - sh
      - -c
      - >
        python manage.py migrate accounts &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:17
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
