# Generated by Django 5.2.4 on 2025-08-08 15:14

from django.db import migrations, transaction
from django.utils.translation import gettext_lazy as _

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('transactions', 'Category')
    EXPENSE = 'EX'
    INCOME = 'IN'
    
    expense_categories = [
        _("Food/Groceries"),
        _("Transportation"),
        _("Utilities"),
        _("Rent/Mortgage"),
        _("Entertainment"),
        _("Healthcare"),
        _("Clothing"),
        _("Education"),
        _("Gifts/Donations"),
        _("Travel"),
        _("Personal Care"),
        _("Insurance"),
        _("Taxes"),
        _("Debt Payments"),
        _("Other Expenses"),
    ]
    
    income_categories = [
        _("Salary"),
        _("Freelance"),
        _("Investments"),
        _("Rental Income"),
        _("Dividends"),
        _("Pension"),
        _("Social Benefits"),
        _("Gifts Received"),
        _("Bonus"),
        _("Other Income"),
    ]
    
    with transaction.atomic():
        for name in expense_categories:
            Category.objects.get_or_create(
                name=name,
                type=EXPENSE,
                user=None,
                defaults={'name': name, 'type': EXPENSE}
            )
        
        for name in income_categories:
            Category.objects.get_or_create(
                name=name,
                type=INCOME,
                user=None,
                defaults={'name': name, 'type': INCOME}
            )
            

class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]